#!/usr/bin/env python3
"""Embed the built web UI (web/dist) into a C++ source so `mlx-mineru --web` can serve it
with no external files. Generates src/cli/web_assets.gen.cpp implementing web_asset() from
include/mineru/web_assets.hpp. If web/dist is absent, emits an empty table (build still works;
--web reports the UI was not bundled).
"""
import os
import sys

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DIST = os.path.join(HERE, "web", "dist")
OUT = os.path.join(HERE, "src", "cli", "web_assets.gen.cpp")

MIME = {
    ".html": "text/html; charset=utf-8", ".js": "text/javascript; charset=utf-8",
    ".css": "text/css; charset=utf-8", ".json": "application/json",
    ".svg": "image/svg+xml", ".png": "image/png", ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg", ".ico": "image/x-icon", ".woff": "font/woff",
    ".woff2": "font/woff2", ".ttf": "font/ttf", ".map": "application/json",
}


def collect():
    files = []
    if not os.path.isdir(DIST):
        return files
    for root, _, names in os.walk(DIST):
        for n in names:
            full = os.path.join(root, n)
            rel = "/" + os.path.relpath(full, DIST).replace(os.sep, "/")
            files.append((rel, full))
    return sorted(files)


def main():
    files = collect()
    lines = [
        "// Generated by scripts/embed_web.py — do not edit.",
        '#include "mineru/web_assets.hpp"',
        "#include <cstring>",
        "namespace mineru {",
        "namespace {",
    ]
    table = []
    for i, (rel, full) in enumerate(files):
        with open(full, "rb") as f:
            data = f.read()
        ext = os.path.splitext(full)[1].lower()
        mime = MIME.get(ext, "application/octet-stream")
        var = f"a{i}"
        # emit bytes as a compact decimal char array
        body = ",".join(str(b) for b in data)
        lines.append(f"const unsigned char {var}[]={{{body}{',' if data else ''}0}};")
        table.append((rel, var, len(data), mime))
    lines.append("struct Entry { const char* path; const unsigned char* data; unsigned long size; const char* mime; };")
    lines.append("const Entry kEntries[] = {")
    for rel, var, n, mime in table:
        lines.append(f'  {{"{rel}", {var}, {n}ul, "{mime}"}},')
    lines.append("};")
    lines.append(f"const int kCount = {len(table)};")
    lines.append("}  // namespace")
    lines.append("""
const WebAsset* web_asset(const std::string& path) {
  static thread_local WebAsset out;
  std::string p = path.empty() ? "/index.html" : path;
  if (p == "/") p = "/index.html";
  for (int i = 0; i < kCount; ++i) {
    if (p == kEntries[i].path) {
      out = {kEntries[i].data, (size_t)kEntries[i].size, kEntries[i].mime};
      return &out;
    }
  }
  return nullptr;
}
bool web_assets_bundled() { return kCount > 0; }
}  // namespace mineru
""")
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    total = sum(n for _, _, n, _ in table)
    print(f"embed_web: {len(files)} files, {total} bytes -> {os.path.relpath(OUT, HERE)}"
          if files else f"embed_web: web/dist missing -> empty {os.path.relpath(OUT, HERE)} (run `pnpm -C web build`)")


if __name__ == "__main__":
    main()
