#!/usr/bin/env python3
"""Emit src/vlm/unicode_tables.hpp with codepoint ranges for the Unicode classes
the Qwen2 pre-tokenizer regex uses: \\p{L} (letters), \\p{N} (numbers),
\\p{White_Space}. Generated from Python's unicodedata so classification matches
the tokenizer's Unicode semantics."""
import os
import sys
import unicodedata

MAXCP = 0x110000


def ranges(pred):
    out = []
    start = None
    for cp in range(MAXCP):
        if pred(cp):
            if start is None:
                start = cp
        else:
            if start is not None:
                out.append((start, cp - 1))
                start = None
    if start is not None:
        out.append((start, MAXCP - 1))
    return out


def is_letter(cp):
    return unicodedata.category(chr(cp)).startswith("L")


def is_number(cp):
    return unicodedata.category(chr(cp)).startswith("N")


# Rust regex \s == \p{White_Space}.
WS = {0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x20, 0x85, 0xA0, 0x1680,
      *range(0x2000, 0x200B), 0x2028, 0x2029, 0x202F, 0x205F, 0x3000}


def is_ws(cp):
    return cp in WS


def emit(name, rngs):
    lines = [f"inline constexpr Range k{name}[] = {{"]
    row = "    "
    for a, b in rngs:
        row += f"{{0x{a:X},0x{b:X}}}, "
        if len(row) > 90:
            lines.append(row.rstrip())
            row = "    "
    if row.strip():
        lines.append(row.rstrip())
    lines.append("};")
    lines.append(f"inline constexpr int k{name}Count = {len(rngs)};")
    return "\n".join(lines)


HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
out_path = os.path.join(HERE, "src", "vlm", "unicode_tables.hpp")

L = ranges(is_letter)
N = ranges(is_number)
W = ranges(is_ws)

header = f"""// Copyright (c) mlx-mineru.
// GENERATED by scripts/gen_unicode_tables.py from Python unicodedata
// (Unicode {unicodedata.unidata_version}). Do not edit by hand.
// Codepoint ranges for the Unicode classes used by the Qwen2 pre-tokenizer.
#pragma once
#include <cstdint>

namespace mineru::ucd {{
struct Range {{ char32_t lo, hi; }};

{emit("Letter", L)}

{emit("Number", N)}

{emit("WhiteSpace", W)}

inline bool in_ranges(char32_t c, const Range* r, int n) {{
  int lo = 0, hi = n - 1;
  while (lo <= hi) {{
    int mid = (lo + hi) / 2;
    if (c < r[mid].lo) hi = mid - 1;
    else if (c > r[mid].hi) lo = mid + 1;
    else return true;
  }}
  return false;
}}
inline bool is_letter(char32_t c) {{ return in_ranges(c, kLetter, kLetterCount); }}
inline bool is_number(char32_t c) {{ return in_ranges(c, kNumber, kNumberCount); }}
inline bool is_whitespace(char32_t c) {{ return in_ranges(c, kWhiteSpace, kWhiteSpaceCount); }}
}}  // namespace mineru::ucd
"""

with open(out_path, "w") as f:
    f.write(header)
print("wrote", out_path, f"(L={len(L)} N={len(N)} WS={len(W)} ranges, Unicode {unicodedata.unidata_version})")
